Support deployment in Public cloud
outscale-dev/osc-k8s-rke-cluster pull request #14
Opened 2022-07-27 09:30 UTC by outscale-mdr

- all nodes have public Ip
- loadbalancer for the kube-apiserver

(See https://github.com/outscale-mdr/osc-k8s-rke-cluster/actions/runs/2745246478 for run proof)

2022-08-01 07:35 UTC, outscale-vbr approved these changes

2022-08-01 07:35 UTC, outscale-vbr commented on control-planes.tf
> +  net_id      = var.public_cloud ? "" : outscale_net.net[0].net_id
why sometimes var.public_cloud ? "" and other it is var.public_cloud ? nil for net_id

2022-08-01 07:45 UTC, outscale-vbr commented on docs/README.md
> +- All nodes have a public IP:
Remove :

2022-08-08 08:57 UTC, jerome-jutteau requested changes

2022-08-08 08:57 UTC, jerome-jutteau commented on control-planes.tf
> +  net_id      = var.public_cloud ? "" : outscale_net.net[0].net_id
"" -> null

2022-09-02 09:44 UTC, outscale-mdr commented
See success of update https://github.com/outscale-mdr/osc-k8s-rke-cluster/actions/runs/2977682512

2022-09-02 12:55 UTC, jerome-jutteau requested changes

2022-09-02 12:55 UTC, jerome-jutteau commented on workers.tf
> +
In public cloud, workers will receive a publique IP even if you don't attach an EIP unless you specify `private_only` tag.
https://docs.outscale.com/en/userguide/About-Instances.html

2022-09-08 09:12 UTC, merged